
[analysisapi]
address = ""
authorizationheadername = ""
authorizationheadervalue = ""
callerapikeyheadername = ""
imageendpoint = ""
videoendpoint = ""

[autoposting]
bottoken = ""
channelid = -10000000000000
edition = ""
filesizethreshold = 20971520
mediaapproximation = 0.08
mediapath = ""
postalertthreshold = 10
similaritythreshold = 6

[documentstore]
authmechanism = "SCRAM-SHA-1"
authsource = ""
databasename = ""
hosts = ["localhost:27017"]
password = ""
replicasetname = ""
useauthentication = false
usereplicaset = false
username = ""

[localization]
language = ""
path = ""

[tdlib]
apihash = ""
apiid = 123456
applicationversion = "1.0.0"
databasedirectory = ""
devicemodel = ""
enablestorageoptimizer = true
filesdirectory = ""
ignorefilenames = true
logverbositylevel = 0
systemlanguagecode = ""
systemversion = ""
usechatinfodatabase = true
usefiledatabase = true
usemessagedatabase = true
usesecretchats = false
usetestdc = false
