name: Go

on: push

jobs:
  format:
    name: Format
    runs-on: self-hosted
    container: ghcr.io/shitpostingio/golang:latest
    steps:

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go fmt
      run: |
        go get -u golang.org/x/lint/golint
        go fmt $(go list ./...)   
    - name: golint
      run: golint -set_exit_status $(go list ./...)

  test:
    name: Test
    runs-on: self-hosted
    container: ghcr.io/shitpostingio/golang:latest
    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go test
      run: go test -v .

  build:
    name: Build
    runs-on: self-hosted
    container: ghcr.io/shitpostingio/golang:latest
    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go build
      run: go build -v .
