name: Go

on: push

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    container: ghcr.io/shitpostingio/golang:latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go fmt
      run: |
        go get -u golang.org/x/lint/golint
        go fmt $(go list ./...)   
    - name: golint
      run: golint -set_exit_status $(go list ./... | grep -v localization)

  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/shitpostingio/golang:latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go test
      run: go test -v .

  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/shitpostingio/golang:latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: go build
      run: go build -v .
    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: autopostingbot
        path: autopostingbot
